#!/usr/bin/env python3
"""One-shot production configuration readiness check.

The script reads environment variables and, by default, also reads a local
``.env`` file without modifying it. Existing process environment variables win.
It exits with status 0 only when every production gate passes.
"""
from __future__ import annotations

import argparse
import os
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Iterable


ROOT = Path(__file__).resolve().parent.parent

FORBIDDEN_SECRET_KEYS = {
    "",
    "dev-only-insecure-key-never-use-in-production",
    "test-only-secret-key",
    "changeme",
    "secret",
    "REPLACE_ME_WITH_64_HEX_CHARS",
    "your-secret-key",
    "please-change-me",
}

FORBIDDEN_PASSWORD_VALUES = {
    "admin",
    "guardian",
    "changeme",
    "password",
    "password123",
    "secret",
    "123456",
    "admin123",
}

DEFAULT_DATABASE_URLS = {
    "sqlite:///security.db",
    "sqlite:///data/security.db",
    "sqlite:///:memory:",
}

TRUTHY = {"1", "true", "yes", "on"}
FALSY = {"0", "false", "no", "off"}


@dataclass(frozen=True)
class CheckResult:
    name: str
    ok: bool
    reason: str


def _load_env_file(path: Path) -> int:
    """Load missing KEY=VALUE pairs from an env file. Never writes the file."""
    if not path.exists():
        return 0
    if not path.is_file():
        raise RuntimeError(f"{path} exists but is not a file")

    loaded = 0
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        if not key or key in os.environ:
            continue
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
            value = value[1:-1]
        os.environ[key] = value
        loaded += 1
    return loaded


def _env(key: str, default: str = "") -> str:
    return (os.environ.get(key, default) or "").strip()


def _is_bool(value: str) -> bool:
    return value.lower() in TRUTHY or value.lower() in FALSY


def _path_from_env(key: str, default: str) -> Path:
    raw = _env(key, default)
    path = Path(raw)
    if not path.is_absolute():
        path = ROOT / path
    return path


def check_flask_env() -> CheckResult:
    value = _env("FLASK_ENV")
    if value != "production":
        return CheckResult(
            "FLASK_ENV",
            False,
            "must be exactly 'production' for this readiness gate",
        )
    return CheckResult("FLASK_ENV", True, "production")


def check_secret_key() -> CheckResult:
    value = _env("SECRET_KEY")
    if not value:
        return CheckResult("SECRET_KEY", False, "missing")
    if value in FORBIDDEN_SECRET_KEYS:
        return CheckResult("SECRET_KEY", False, "uses a default/example value")
    if len(value) < 32:
        return CheckResult("SECRET_KEY", False, "must be at least 32 characters")
    return CheckResult("SECRET_KEY", True, "set and non-default")


def check_admin_password_hash() -> CheckResult:
    value = _env("ADMIN_PASSWORD_HASH")
    if not value:
        return CheckResult("ADMIN_PASSWORD_HASH", False, "missing")
    if value.lower() in FORBIDDEN_PASSWORD_VALUES:
        return CheckResult(
            "ADMIN_PASSWORD_HASH",
            False,
            "looks like a default/plain password instead of a hash",
        )
    if not (value.startswith("pbkdf2:") or value.startswith("scrypt:")) or "$" not in value:
        return CheckResult(
            "ADMIN_PASSWORD_HASH",
            False,
            "must be a Werkzeug password hash generated by scripts/generate_admin_password_hash.py",
        )
    try:
        from werkzeug.security import check_password_hash
    except ImportError:
        return CheckResult(
            "ADMIN_PASSWORD_HASH",
            False,
            "cannot validate default passwords because Werkzeug is not installed",
        )
    for candidate in FORBIDDEN_PASSWORD_VALUES:
        try:
            if check_password_hash(value, candidate):
                return CheckResult(
                    "ADMIN_PASSWORD_HASH",
                    False,
                    "hash matches a known default password",
                )
        except ValueError:
            return CheckResult("ADMIN_PASSWORD_HASH", False, "hash format is invalid")
    return CheckResult("ADMIN_PASSWORD_HASH", True, "hash configured")


def check_plain_admin_password() -> CheckResult:
    value = _env("ADMIN_PASSWORD")
    if value:
        reason = "production must not define plaintext ADMIN_PASSWORD"
        if value.lower() in FORBIDDEN_PASSWORD_VALUES:
            reason += "; current value is a known default"
        return CheckResult("ADMIN_PASSWORD", False, reason)
    return CheckResult("ADMIN_PASSWORD", True, "not set")


def check_database_url() -> CheckResult:
    value = _env("DATABASE_URL")
    if not value:
        return CheckResult("DATABASE_URL", False, "missing")
    if value in DEFAULT_DATABASE_URLS:
        return CheckResult("DATABASE_URL", False, "uses a local/default SQLite URL")
    if "://" not in value:
        return CheckResult("DATABASE_URL", False, "does not look like a database URL")
    return CheckResult("DATABASE_URL", True, "configured")


def check_redis_password() -> CheckResult:
    value = _env("REDIS_PASSWORD")
    if not value:
        return CheckResult("REDIS_PASSWORD", False, "missing")
    if value.lower() in FORBIDDEN_PASSWORD_VALUES:
        return CheckResult("REDIS_PASSWORD", False, "uses a default/weak password")
    if len(value) < 12:
        return CheckResult("REDIS_PASSWORD", False, "must be at least 12 characters")
    return CheckResult("REDIS_PASSWORD", True, "set and non-default")


def check_allowed_origins() -> CheckResult:
    value = _env("ALLOWED_ORIGINS")
    if not value:
        return CheckResult("ALLOWED_ORIGINS", False, "missing")
    origins = [part.strip() for part in value.split(",") if part.strip()]
    if not origins:
        return CheckResult("ALLOWED_ORIGINS", False, "contains no usable origins")
    if any(origin == "*" for origin in origins):
        return CheckResult("ALLOWED_ORIGINS", False, "wildcard '*' is forbidden")
    invalid = [
        origin
        for origin in origins
        if not (origin.lower().startswith("http://") or origin.lower().startswith("https://"))
    ]
    if invalid:
        return CheckResult("ALLOWED_ORIGINS", False, f"invalid origin: {invalid[0]}")
    return CheckResult("ALLOWED_ORIGINS", True, f"{len(origins)} origin(s) configured")


def check_dry_run() -> CheckResult:
    value = _env("DRY_RUN")
    if not value:
        return CheckResult("DRY_RUN", False, "missing; production must set DRY_RUN=false explicitly")
    if not _is_bool(value):
        return CheckResult("DRY_RUN", False, "must be true or false")
    if value.lower() in TRUTHY:
        return CheckResult("DRY_RUN", False, "must be false for production readiness")
    return CheckResult("DRY_RUN", True, "false")


def check_model_dir() -> CheckResult:
    model_dir = _path_from_env("MODEL_DIR", "models/saved")
    if not model_dir.exists():
        return CheckResult("MODEL_DIR", False, f"directory does not exist: {model_dir}")
    if not model_dir.is_dir():
        return CheckResult("MODEL_DIR", False, f"not a directory: {model_dir}")
    try:
        has_content = any(model_dir.iterdir())
    except OSError as exc:
        return CheckResult("MODEL_DIR", False, f"cannot read directory: {exc}")
    if not has_content:
        return CheckResult("MODEL_DIR", False, f"directory is empty: {model_dir}")
    return CheckResult("MODEL_DIR", True, f"directory exists: {model_dir}")


def check_log_integrity() -> CheckResult:
    value = _env("LOG_INTEGRITY_ENABLED")
    if not value:
        return CheckResult("LOG_INTEGRITY_ENABLED", False, "missing; production must set true")
    if not _is_bool(value):
        return CheckResult("LOG_INTEGRITY_ENABLED", False, "must be true or false")
    if value.lower() not in TRUTHY:
        return CheckResult("LOG_INTEGRITY_ENABLED", False, "must be true in production")
    return CheckResult("LOG_INTEGRITY_ENABLED", True, "true")


def check_log_dir() -> CheckResult:
    log_dir = _path_from_env("LOG_DIR", "logs")
    if not log_dir.exists():
        return CheckResult("LOG_DIR", False, f"directory does not exist: {log_dir}")
    if not log_dir.is_dir():
        return CheckResult("LOG_DIR", False, f"not a directory: {log_dir}")
    if not os.access(log_dir, os.W_OK):
        return CheckResult("LOG_DIR", False, f"directory is not writable: {log_dir}")
    return CheckResult("LOG_DIR", True, f"directory exists and is writable: {log_dir}")


def _checks() -> Iterable[Callable[[], CheckResult]]:
    return (
        check_flask_env,
        check_secret_key,
        check_admin_password_hash,
        check_plain_admin_password,
        check_database_url,
        check_redis_password,
        check_allowed_origins,
        check_dry_run,
        check_model_dir,
        check_log_integrity,
        check_log_dir,
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Validate AI-Security-Guardian production configuration."
    )
    parser.add_argument(
        "--env-file",
        default=str(ROOT / ".env"),
        help="optional env file to read without overriding existing variables (default: .env)",
    )
    parser.add_argument(
        "--skip-env-file",
        action="store_true",
        help="use only the current process environment",
    )
    args = parser.parse_args(argv)

    if not args.skip_env_file:
        env_path = Path(args.env_file)
        if not env_path.is_absolute():
            env_path = ROOT / env_path
        try:
            loaded = _load_env_file(env_path)
        except RuntimeError as exc:
            print(f"[FAIL] ENV_FILE: {exc}")
            return 1
        print(f"Env file: {env_path} ({loaded} value(s) loaded, existing env preserved)")
    else:
        print("Env file: skipped")

    print("AI-Security-Guardian production readiness check")
    print("-" * 56)

    results = [check() for check in _checks()]
    for result in results:
        status = "PASS" if result.ok else "FAIL"
        print(f"[{status}] {result.name}: {result.reason}")

    failures = [result for result in results if not result.ok]
    print("-" * 56)
    if failures:
        print(f"Result: FAIL ({len(failures)} issue(s))")
        return 1

    print("Result: PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
