#!/usr/bin/env python3
"""Start local PostgreSQL and Redis dependencies with explicit port handling."""
from __future__ import annotations

import argparse
import os
import socket
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

from sqlalchemy import create_engine, text
from sqlalchemy.engine import make_url


if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(line_buffering=True)

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_ENV_FILE = ROOT / ".env.host-nondegraded.example"
DEFAULT_RUNTIME_ENV_FILE = ROOT / "tmp" / "local-deps.env"
DEFAULT_PROJECT_NAME = "ai-security-guardian-local-deps"
COMPOSE_FILE = ROOT / "docker-compose.local-deps.yml"


@dataclass(frozen=True)
class PortHealth:
    healthy: bool
    reason: str


def _load_env(path: Path) -> dict[str, str]:
    if not path.exists():
        raise RuntimeError(f"env file not found: {path}")
    env: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        env[key.strip()] = value.strip().strip("'\"")
    return env


def _write_env(path: Path, env: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    keys = [
        "FLASK_ENV",
        "DATABASE_URL",
        "LOCAL_POSTGRES_PORT",
        "LOCAL_POSTGRES_DB",
        "LOCAL_POSTGRES_USER",
        "LOCAL_POSTGRES_PASSWORD",
        "LOCAL_REDIS_PORT",
        "REDIS_HOST",
        "REDIS_PORT",
        "REDIS_DB",
        "REDIS_PASSWORD",
        "GUARDIAN_REDIS_DISABLE_CONNECT",
        "REQUIRE_REDIS_AVAILABLE",
        "REQUIRE_MODELS_READY",
        "RUNTIME_GUARDS_ENABLED",
        "MODEL_DIR",
    ]
    lines = [
        "# Generated by scripts/start_local_deps.py.",
        "# Use this file for verification after an alternate-port start.",
        "",
    ]
    for key in keys:
        if key in env:
            lines.append(f"{key}={env[key]}")
    extra_keys = sorted(key for key in env if key not in keys)
    if extra_keys:
        lines.append("")
        for key in extra_keys:
            lines.append(f"{key}={env[key]}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _require_env(env: dict[str, str], key: str) -> str:
    value = env.get(key, "").strip()
    if not value:
        raise RuntimeError(f"{key} is required for local dependencies")
    return value


def _postgres_port(env: dict[str, str]) -> int:
    port = int(_require_env(env, "LOCAL_POSTGRES_PORT"))
    url = make_url(_require_env(env, "DATABASE_URL"))
    if (url.host or "").lower() != "127.0.0.1":
        raise RuntimeError("DATABASE_URL must use 127.0.0.1 for host local deps")
    if url.get_backend_name() != "postgresql":
        raise RuntimeError(f"DATABASE_URL must be PostgreSQL, got {url.get_backend_name()!r}")
    if int(url.port or 0) != port:
        raise RuntimeError(
            "DATABASE_URL port does not match LOCAL_POSTGRES_PORT: "
            f"{url.port!r} != {port}"
        )
    return port


def _redis_port(env: dict[str, str]) -> int:
    port = int(_require_env(env, "LOCAL_REDIS_PORT"))
    redis_port = int(_require_env(env, "REDIS_PORT"))
    if env.get("REDIS_HOST", "").lower() != "127.0.0.1":
        raise RuntimeError("REDIS_HOST must be 127.0.0.1 for host local deps")
    if redis_port != port:
        raise RuntimeError(
            f"REDIS_PORT does not match LOCAL_REDIS_PORT: {redis_port} != {port}"
        )
    _require_env(env, "REDIS_PASSWORD")
    return port


def _set_database_port(env: dict[str, str], port: int) -> None:
    url = make_url(_require_env(env, "DATABASE_URL"))
    env["DATABASE_URL"] = url.set(port=port).render_as_string(hide_password=False)
    env["LOCAL_POSTGRES_PORT"] = str(port)


def _set_redis_port(env: dict[str, str], port: int) -> None:
    env["LOCAL_REDIS_PORT"] = str(port)
    env["REDIS_PORT"] = str(port)


def _port_is_free(port: int) -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        try:
            sock.bind(("127.0.0.1", port))
        except OSError:
            return False
    return True


def _next_free_port(start: int) -> int:
    for port in range(start, start + 1000):
        if _port_is_free(port):
            return port
    raise RuntimeError(f"no free local port found from {start} to {start + 999}")


def _postgres_health(env: dict[str, str]) -> PortHealth:
    try:
        engine = create_engine(
            _require_env(env, "DATABASE_URL"),
            pool_pre_ping=True,
            connect_args={"connect_timeout": 2},
        )
        try:
            with engine.connect() as conn:
                conn.execute(text("select 1")).scalar_one()
        finally:
            engine.dispose()
        return PortHealth(True, "healthy PostgreSQL matched DATABASE_URL")
    except Exception as exc:  # noqa: BLE001
        return PortHealth(False, f"not a healthy PostgreSQL for this env: {exc}")


def _redis_health(env: dict[str, str]) -> PortHealth:
    try:
        import redis

        client = redis.Redis(
            host="127.0.0.1",
            port=int(_require_env(env, "REDIS_PORT")),
            db=int(env.get("REDIS_DB", "0")),
            password=_require_env(env, "REDIS_PASSWORD"),
            socket_connect_timeout=2,
            socket_timeout=2,
            decode_responses=True,
        )
        if client.ping() is not True:
            return PortHealth(False, "Redis AUTH PING did not return PONG")
        return PortHealth(True, "healthy Redis matched REDIS_PASSWORD")
    except Exception as exc:  # noqa: BLE001
        return PortHealth(False, f"not a healthy Redis for this env: {exc}")


def _docker_port_owners(port: int) -> str:
    proc = subprocess.run(
        ["docker", "ps", "--format", "{{.Names}}\t{{.Ports}}"],
        cwd=ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        check=False,
    )
    needle = f":{port}->"
    owners = [
        line.split("\t", 1)[0]
        for line in proc.stdout.splitlines()
        if needle in line
    ]
    return ", ".join(owners) if owners else "non-Docker process or unknown Docker owner"


def _compose_base(project_name: str, env_file: Path) -> list[str]:
    return [
        "docker",
        "compose",
        "-p",
        project_name,
        "--env-file",
        str(env_file),
        "-f",
        str(COMPOSE_FILE),
    ]


def _cleanup_created_containers(project_name: str) -> None:
    proc = subprocess.run(
        [
            "docker",
            "ps",
            "-a",
            "--filter",
            f"label=com.docker.compose.project={project_name}",
            "--filter",
            "status=created",
            "--format",
            "{{.ID}}\t{{.Names}}",
        ],
        cwd=ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    ids = [line.split("\t", 1)[0] for line in proc.stdout.splitlines() if line.strip()]
    if not ids:
        return
    names = [line.split("\t", 1)[1] for line in proc.stdout.splitlines() if "\t" in line]
    print("Removing Created local-deps containers: " + ", ".join(names))
    subprocess.run(["docker", "rm", "-f", *ids], cwd=ROOT, check=False)


def _run_compose_up(project_name: str, env_file: Path) -> None:
    cmd = _compose_base(project_name, env_file) + [
        "up",
        "-d",
        "--wait",
        "--wait-timeout",
        "90",
    ]
    print("Starting local dependencies with docker compose.")
    proc = subprocess.run(cmd, cwd=ROOT, text=True)
    if proc.returncode != 0:
        _cleanup_created_containers(project_name)
        raise RuntimeError(f"docker compose up failed with exit code {proc.returncode}")


def _run_verify(env_file: Path) -> None:
    subprocess.run(
        [sys.executable, str(ROOT / "scripts" / "verify_local_deps.py"), str(env_file)],
        cwd=ROOT,
        check=True,
    )


def _preflight(env: dict[str, str]) -> tuple[int, int, bool, bool]:
    pg_port = _postgres_port(env)
    redis_port = _redis_port(env)
    pg_free = _port_is_free(pg_port)
    redis_free = _port_is_free(redis_port)
    return pg_port, redis_port, pg_free, redis_free


def _print_conflict(
    pg_port: int,
    redis_port: int,
    pg_free: bool,
    redis_free: bool,
    pg_health: PortHealth,
    redis_health: PortHealth,
) -> None:
    if not pg_free:
        print(
            f"Port {pg_port} is occupied by {_docker_port_owners(pg_port)}; "
            f"PostgreSQL reuse check: {pg_health.reason}"
        )
    if not redis_free:
        print(
            f"Port {redis_port} is occupied by {_docker_port_owners(redis_port)}; "
            f"Redis reuse check: {redis_health.reason}"
        )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Start local PostgreSQL/Redis deps without leaving Created containers."
    )
    parser.add_argument("--env-file", default=str(DEFAULT_ENV_FILE))
    parser.add_argument("--project-name", default=DEFAULT_PROJECT_NAME)
    parser.add_argument(
        "--port-strategy",
        choices=("reuse-or-fail", "alternate", "fail"),
        default="reuse-or-fail",
        help=(
            "reuse-or-fail reuses already healthy configured ports; alternate writes "
            "an updated env file with free ports; fail stops on any occupied port"
        ),
    )
    parser.add_argument(
        "--runtime-env-file",
        default=str(DEFAULT_RUNTIME_ENV_FILE),
        help="env file written when --port-strategy alternate changes ports",
    )
    parser.add_argument("--no-verify", action="store_true")
    args = parser.parse_args(argv)

    env_file = Path(args.env_file)
    if not env_file.is_absolute():
        env_file = ROOT / env_file
    runtime_env_file = Path(args.runtime_env_file)
    if not runtime_env_file.is_absolute():
        runtime_env_file = ROOT / runtime_env_file

    env = _load_env(env_file)
    pg_port, redis_port, pg_free, redis_free = _preflight(env)

    if pg_free and redis_free:
        active_env_file = env_file
        print(f"Ports are free: PostgreSQL {pg_port}, Redis {redis_port}.")
        _run_compose_up(args.project_name, active_env_file)
    else:
        pg_health = _postgres_health(env) if not pg_free else PortHealth(False, "port is free")
        redis_health = _redis_health(env) if not redis_free else PortHealth(False, "port is free")
        _print_conflict(pg_port, redis_port, pg_free, redis_free, pg_health, redis_health)

        if args.port_strategy == "fail":
            _cleanup_created_containers(args.project_name)
            raise RuntimeError("configured local dependency port is occupied")

        if (
            args.port_strategy == "reuse-or-fail"
            and (pg_free or pg_health.healthy)
            and (redis_free or redis_health.healthy)
            and not (pg_free or redis_free)
        ):
            active_env_file = env_file
            print("Reusing existing healthy PostgreSQL and Redis on configured ports.")
        elif args.port_strategy == "alternate":
            if not pg_free:
                _set_database_port(env, _next_free_port(pg_port + 1))
            if not redis_free:
                _set_redis_port(env, _next_free_port(redis_port + 1))
            _write_env(runtime_env_file, env)
            active_env_file = runtime_env_file
            print(
                "Using alternate local dependency ports and wrote updated env: "
                f"{active_env_file}"
            )
            print(
                "Updated ports: PostgreSQL "
                f"{env['LOCAL_POSTGRES_PORT']}, Redis {env['LOCAL_REDIS_PORT']}"
            )
            _run_compose_up(args.project_name, active_env_file)
        else:
            _cleanup_created_containers(args.project_name)
            raise RuntimeError(
                "configured port is occupied and cannot be safely reused. "
                "Use --port-strategy alternate to write an updated env file, or stop "
                "the conflicting dependency yourself."
            )

    _cleanup_created_containers(args.project_name)
    if not args.no_verify:
        _run_verify(active_env_file)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except RuntimeError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        raise SystemExit(2)
